export const vietnamData = {
  "Hồ Chí Minh": [
    "Quận 1",
    "Quận 3",
    "Quận 4",
    "Quận 5",
    "Quận 6",
    "Quận 7",
    "Quận 8",
    "Quận 10",
    "Quận 11",
    "Quận 12",
    "Tân Bình",
    "Bình Tân",
    "Phú Nhuận",
    "Gò Vấp",
    "Bình Thạnh",
    "Tân Phú",
    "Thành phố Thủ Đức",
    "Huyện Củ Chi",
    "Huyện Hóc Môn",
    "Huyện Bình Chánh",
    "Huyện Nhà Bè",
    "Huyện Cần Giờ",
  ],
  "Hà Nội": [
    "Quận Ba Đình",
    "Quận Hoàn Kiếm",
    "Quận Tây Hồ",
    "Quận Long Biên",
    "Quận Cầu Giấy",
    "Quận Đống Đa",
    "Quận Hai Bà Trưng",
    "Quận Hoàng Mai",
    "Quận Thanh Xuân",
    "Quận Hà Đông",
    "Quận Bắc Từ Liêm",
    "Quận Nam Từ Liêm",
  ],
  "Đà Nẵng": [
    "Quận Hải Châu",
    "Quận Thanh Khê",
    "Quận Sơn Trà",
    "Quận Ngũ Hành Sơn",
    "Quận Liên Chiểu",
    "Quận Cẩm Lệ",
    "Huyện Hòa Vang",
  ],
  "Hải Phòng": [
    "Quận Hồng Bàng",
    "Quận Ngô Quyền",
    "Quận Lê Chân",
    "Quận Hải An",
    "Quận Kiến An",
    "Quận Đồ Sơn",
    "Quận Dương Kinh",
    "Huyện Thủy Nguyên",
  ],
  "Cần Thơ": [
    "Quận Ninh Kiều",
    "Quận Bình Thủy",
    "Quận Cái Răng",
    "Quận Ô Môn",
    "Quận Thốt Nốt",
  ],
  "Đồng Nai": [
    "Thành phố Biên Hòa",
    "Thành phố Long Khánh",
    "Huyện Long Thành",
    "Huyện Nhơn Trạch",
    "Huyện Trảng Bom",
    "Huyện Thống Nhất",
  ],
  "Bình Dương": [
    "Thành phố Thủ Dầu Một",
    "Thành phố Dĩ An",
    "Thành phố Thuận An",
    "Thành phố Tân Uyên",
    "Thị xã Bến Cát",
    "Huyện Bàu Bàng",
  ],
  "Bà Rịa - Vũng Tàu": [
    "Thành phố Vũng Tàu",
    "Thành phố Bà Rịa",
    "Thị xã Phú Mỹ",
    "Huyện Châu Đức",
    "Huyện Xuyên Mộc",
  ],
  "Bắc Ninh": [
    "Thành phố Bắc Ninh",
    "Thành phố Từ Sơn",
    "Huyện Tiên Du",
    "Huyện Yên Phong",
    "Huyện Quế Võ",
    "Huyện Thuận Thành",
  ],
  "Quảng Ninh": [
    "Thành phố Hạ Long",
    "Thành phố Cẩm Phả",
    "Thành phố Uông Bí",
    "Thành phố Móng Cái",
    "Thị xã Đông Triều",
    "Thị xã Quảng Yên",
  ],
};

export const provinces = Object.keys(vietnamData);
